### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Brekkis** [AMiketta/wbec-ios#1]
Can you make a small how-to-install- Instruction! This will help! 

Regards Stefan

**Comment by AMiketta** [comment]
Hi there ist an complete website about the project i am forked from :-) https://steff393.github.io/wbec-site/ 
I hope that it will help you

**Comment by Brekkis** [comment]
I already have wbec from steff393 running, but i unterstand this fork, that you have developed an iOS-App for wbec, or did i missunderstood that? 
for this i need help to install.

regards

**Comment by AMiketta** [comment]
Oh yes i have overseen that you commented to the IOS branch an not to my fork from the wbec project. In General you will need to run XCode on an apple computer to compile this app by yourself... Apple it only allows to distribute apps via the Appstore and that will cost me at least 100€ per year, so i currently have no plans to release this app to apples app store at the moment.
